//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmaPosAdminProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class productImage
    {
        public int id { get; set; }
        public Nullable<int> productId { get; set; }
        public string image { get; set; }
        public Nullable<int> orderNumber { get; set; }
    
        public virtual product product { get; set; }
    }
}
